spring.datasource.url=jdbc:mysql://localhost:3306/transito?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=96952650

spring.jpa.show-sql=true